/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        gray: {
          50: "hsl(var(--muted) / 0.28)",
          100: "hsl(var(--muted) / 0.42)",
          200: "hsl(var(--muted) / 0.62)",
          300: "hsl(var(--border) / 0.78)",
          400: "hsl(var(--muted-foreground) / 0.58)",
          500: "hsl(var(--muted-foreground) / 0.78)",
          600: "hsl(var(--muted-foreground) / 0.9)",
          700: "hsl(var(--foreground) / 0.86)",
          800: "hsl(var(--foreground) / 0.94)",
          900: "hsl(var(--foreground) / 1)",
        },
        blue: {
          50: "hsl(var(--accent) / 0.08)",
          100: "hsl(var(--accent) / 0.14)",
          200: "hsl(var(--accent) / 0.22)",
          500: "hsl(var(--accent) / 1)",
          600: "hsl(var(--accent) / 1)",
          700: "hsl(var(--accent) / 1)",
        },
        green: {
          50: "hsl(var(--success) / 0.08)",
          100: "hsl(var(--success) / 0.14)",
          200: "hsl(var(--success) / 0.22)",
          500: "hsl(var(--success) / 1)",
          600: "hsl(var(--success) / 1)",
          700: "hsl(var(--success) / 1)",
          800: "hsl(var(--success) / 1)",
        },
        red: {
          50: "hsl(var(--destructive) / 0.08)",
          100: "hsl(var(--destructive) / 0.14)",
          200: "hsl(var(--destructive) / 0.22)",
          500: "hsl(var(--destructive) / 1)",
          600: "hsl(var(--destructive) / 1)",
          700: "hsl(var(--destructive) / 1)",
          800: "hsl(var(--destructive) / 1)",
        },
        orange: {
          50: "hsl(var(--warning) / 0.08)",
          100: "hsl(var(--warning) / 0.14)",
          200: "hsl(var(--warning) / 0.22)",
          500: "hsl(var(--warning) / 1)",
          600: "hsl(var(--warning) / 1)",
          700: "hsl(var(--warning) / 1)",
          800: "hsl(var(--warning) / 1)",
        },
        yellow: {
          50: "hsl(var(--warning) / 0.08)",
          100: "hsl(var(--warning) / 0.14)",
          200: "hsl(var(--warning) / 0.22)",
          500: "hsl(var(--warning) / 1)",
          600: "hsl(var(--warning) / 1)",
          700: "hsl(var(--warning) / 1)",
          800: "hsl(var(--warning) / 1)",
        },
        purple: {
          50: "color-mix(in oklab, hsl(var(--accent)) 8%, hsl(var(--card)))",
          100: "color-mix(in oklab, hsl(var(--accent)) 14%, hsl(var(--card)))",
          200: "color-mix(in oklab, hsl(var(--accent)) 22%, hsl(var(--card)))",
          500: "color-mix(in oklab, hsl(var(--accent)) 68%, hsl(var(--secondary)) 32%)",
          600: "color-mix(in oklab, hsl(var(--accent)) 68%, hsl(var(--secondary)) 32%)",
          700: "color-mix(in oklab, hsl(var(--accent)) 68%, hsl(var(--secondary)) 32%)",
          800: "color-mix(in oklab, hsl(var(--accent)) 68%, hsl(var(--secondary)) 32%)",
        },
        danger: {
          50: "hsl(var(--destructive) / 0.08)",
          100: "hsl(var(--destructive) / 0.14)",
          200: "hsl(var(--destructive) / 0.22)",
          500: "hsl(var(--destructive) / 1)",
          600: "hsl(var(--destructive) / 1)",
          700: "hsl(var(--destructive) / 1)",
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        border: "hsl(var(--border) / <alpha-value>)",
        input: "hsl(var(--input) / <alpha-value>)",
        ring: "hsl(var(--ring) / <alpha-value>)",
        background: "hsl(var(--background) / <alpha-value>)",
        foreground: "hsl(var(--foreground) / <alpha-value>)",
        card: {
          50: "hsl(var(--card) / 0.5)",
          100: "hsl(var(--card) / 0.7)",
          500: "hsl(var(--card) / 1)",
          DEFAULT: "hsl(var(--card) / <alpha-value>)",
          foreground: "hsl(var(--card-foreground) / <alpha-value>)",
        },
        popover: {
          DEFAULT: "hsl(var(--popover) / <alpha-value>)",
          foreground: "hsl(var(--popover-foreground) / <alpha-value>)",
        },
        primary: {
          50: "hsl(var(--primary) / 0.08)",
          100: "hsl(var(--primary) / 0.14)",
          200: "hsl(var(--primary) / 0.22)",
          300: "hsl(var(--primary) / 0.32)",
          500: "hsl(var(--primary) / 1)",
          600: "hsl(var(--primary) / 1)",
          700: "hsl(var(--primary) / 1)",
          DEFAULT: "hsl(var(--primary) / <alpha-value>)",
          foreground: "hsl(var(--primary-foreground) / <alpha-value>)",
        },
        secondary: {
          50: "hsl(var(--secondary) / 0.08)",
          100: "hsl(var(--secondary) / 0.14)",
          200: "hsl(var(--secondary) / 0.22)",
          500: "hsl(var(--secondary) / 1)",
          600: "hsl(var(--secondary) / 1)",
          700: "hsl(var(--secondary) / 1)",
          DEFAULT: "hsl(var(--secondary) / <alpha-value>)",
          foreground: "hsl(var(--secondary-foreground) / <alpha-value>)",
        },
        accent: {
          50: "hsl(var(--accent) / 0.08)",
          100: "hsl(var(--accent) / 0.14)",
          200: "hsl(var(--accent) / 0.22)",
          500: "hsl(var(--accent) / 1)",
          600: "hsl(var(--accent) / 1)",
          DEFAULT: "hsl(var(--accent) / <alpha-value>)",
          foreground: "hsl(var(--accent-foreground) / <alpha-value>)",
        },
        muted: {
          50: "hsl(var(--muted) / 0.35)",
          100: "hsl(var(--muted) / 0.55)",
          200: "hsl(var(--muted) / 0.8)",
          500: "hsl(var(--muted) / 1)",
          DEFAULT: "hsl(var(--muted) / <alpha-value>)",
          foreground: "hsl(var(--muted-foreground) / <alpha-value>)",
        },
        destructive: {
          50: "hsl(var(--destructive) / 0.08)",
          100: "hsl(var(--destructive) / 0.14)",
          200: "hsl(var(--destructive) / 0.22)",
          500: "hsl(var(--destructive) / 1)",
          600: "hsl(var(--destructive) / 1)",
          700: "hsl(var(--destructive) / 1)",
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        success: {
          50: "hsl(var(--success) / 0.08)",
          100: "hsl(var(--success) / 0.14)",
          200: "hsl(var(--success) / 0.22)",
          500: "hsl(var(--success) / 1)",
          600: "hsl(var(--success) / 1)",
          700: "hsl(var(--success) / 1)",
          DEFAULT: "hsl(var(--success) / <alpha-value>)",
          foreground: "hsl(var(--success-foreground) / <alpha-value>)",
        },
        warning: {
          50: "hsl(var(--warning) / 0.08)",
          100: "hsl(var(--warning) / 0.14)",
          200: "hsl(var(--warning) / 0.22)",
          500: "hsl(var(--warning) / 1)",
          600: "hsl(var(--warning) / 1)",
          700: "hsl(var(--warning) / 1)",
          DEFAULT: "hsl(var(--warning) / <alpha-value>)",
          foreground: "hsl(var(--warning-foreground) / <alpha-value>)",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background) / <alpha-value>)",
          foreground: "hsl(var(--sidebar-foreground) / <alpha-value>)",
          border: "hsl(var(--sidebar-border) / <alpha-value>)",
          accent: "hsl(var(--sidebar-accent) / <alpha-value>)",
        },
      },
      borderRadius: {
        xl: "calc(var(--radius) - 0.25rem)",
        "2xl": "var(--radius)",
        "3xl": "calc(var(--radius) + 0.65rem)",
        "4xl": "calc(var(--radius) + 1rem)",
      },
      fontFamily: {
        display: ["var(--font-display)"],
        sans: ["var(--font-sans)"],
        arabic: ["var(--font-arabic)"],
        mono: ["var(--font-mono)"],
        numeric: ["var(--font-numeric)"],
      },
      boxShadow: {
        soft: "0 16px 60px -24px hsl(var(--shadow-color) / 0.22)",
        card: "0 24px 70px -30px hsl(var(--shadow-color) / 0.3)",
        glow: "0 0 0 1px rgba(255,255,255,0.35), 0 18px 60px -26px hsl(var(--primary) / 0.45)",
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-10px)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        "shake-soft": {
          "0%, 100%": { transform: "translateX(0)" },
          "20%": { transform: "translateX(-6px)" },
          "40%": { transform: "translateX(5px)" },
          "60%": { transform: "translateX(-4px)" },
          "80%": { transform: "translateX(3px)" },
        },
      },
      animation: {
        float: "float 6s ease-in-out infinite",
        shimmer: "shimmer 1.65s linear infinite",
        "shake-soft": "shake-soft 0.5s ease-in-out",
      },
    },
  },
  plugins: [],
};
